In [9]:
import pandas as pd
import numpy as np

In [10]:
tree_equity = pd.read_csv('/Users/shriyakatta/UTD-Deep-Dive-AI-Project/Dataset_Files/tx_tes_cleaned_v2.csv')
tree_equity.columns

Index(['GEOID', 'place', 'state', 'state_abbr', 'county', 'ua_name',
       'congressio', 'land_area', 'biome', 'tc_goal', 'treecanopy', 'tc_gap',
       'priority_i', 'pctpocnorm', 'pctpovnorm', 'unemplnorm', 'dep_perc',
       'depratnorm', 'health_nor', 'temp_norm', 'tes', 'tesctyscor',
       'holc_grade', 'ej_disadva', '_bld1200', '_veg1200', '_tot1200',
       '_bld1500', '_veg1500', '_tot1500', '_bld1800', '_veg1800', '_tot1800',
       'rank', 'rankgrpsz'],
      dtype='object')

In [11]:
remove_col = ['GEOID', 'place', 'state', 'state_abbr', 'ua_name', 'congressio', 'holc_grade', 'ej_disadva', '_bld1200', '_veg1200', '_tot1200', '_bld1500', '_veg1500', '_tot1500', '_bld1800', '_veg1800', '_tot1800']
tree_equity = tree_equity.drop(columns=remove_col)
print(tree_equity.columns)
tree_equity.head()

Index(['county', 'land_area', 'biome', 'tc_goal', 'treecanopy', 'tc_gap',
       'priority_i', 'pctpocnorm', 'pctpovnorm', 'unemplnorm', 'dep_perc',
       'depratnorm', 'health_nor', 'temp_norm', 'tes', 'tesctyscor', 'rank',
       'rankgrpsz'],
      dtype='object')

,county,land_area,biome,tc_goal,treecanopy,tc_gap,priority_i,pctpocnorm,pctpovnorm,unemplnorm,dep_perc,depratnorm,health_nor,temp_norm,tes,tesctyscor,rank,rankgrpsz
0,Anderson County,1.2827,Forest,0.5,0.4475,0.0525,0.507741,0.303300,0.283496,0.000000,0.508665,0.694816,0.465671,0.528401,91,86.0,17,24
1,Anderson County,2.1241,Forest,0.5,0.5791,0.0000,0.639673,0.858020,0.910096,0.656915,0.352505,0.281079,0.465671,0.130045,100,86.0,1,24
2,Anderson County,2.5378,Forest,0.5,0.4195,0.0805,0.561506,0.734242,0.486781,0.070550,0.412879,0.414940,0.465671,0.521674,86,86.0,18,24
3,Anderson County,3.2225,Forest,0.5,0.6449,0.0000,0.517795,0.476606,0.443385,0.000000,0.554441,0.871067,0.465671,0.097160,100,86.0,1,24
4,Anderson County,2.7991,Forest,0.5,0.5738,0.0000,0.526463,0.534323,0.950673,0.205986,0.406532,0.399588,0.968750,0.195067,100,86.0,1,24

In [12]:
tree_equity.to_csv("Tree_Equity_Counties.csv")

In [29]:
temp_rain = pd.read_csv('/Users/shriyakatta/UTD-Deep-Dive-AI-Project/Dataset_Files/Temperature_Rainfall.csv')

merged = tree_equity.merge(temp_rain, left_on = "county", right_on = 'Name', how = 'left')
merged = merged.drop(columns = ['Unnamed: 0', 'Name'])
print(merged.shape)
print(merged.columns)
merged.info()

(16011, 28)
Index(['county', 'land_area', 'biome', 'tc_goal', 'treecanopy', 'tc_gap',
       'priority_i', 'pctpocnorm', 'pctpovnorm', 'unemplnorm', 'dep_perc',
       'depratnorm', 'health_nor', 'temp_norm', 'tes', 'tesctyscor', 'rank',
       'rankgrpsz', 'Mean_Temp', 'Median_Temp', 'STD_Temp', 'Min_Temp',
       'Max_Temp', 'Mean_Rain', 'Median_Rain', 'STD_Rain', 'Min_Rain',
       'Max_Rain'],
      dtype='object')
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16011 entries, 0 to 16010
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   county       16011 non-null  object
 1   land_area    16011 non-null  float64
 2   biome        16011 non-null  object
 3   tc_goal      16011 non-null  float64
 4   treecanopy   16011 non-null  float64
 5   tc_gap       16011 non-null  float64
 6   priority_i   16011 non-null  float64
 7   pctpocnorm   16011 non-null  float64
 8   pctpovnorm   16011 non-null  float64
 9   unemplnorm   16011 non-null  float64
 10  dep_perc     16011 non-null  float64
 11  depratnorm   16011 non-null  float64
 12  health_nor   16011 non-null  float64
 13  temp_norm    16011 non-null  float64
 14  tes          16011 non-null  int64
 15  tesctyscor   16011 non-null  float64
 16  rank         16011 non-null  int64
 17  rankgrpsz    16011 non-null  int64
 18  Mean_Temp    16011 non-null  float64
 19  Median_Temp  16011 non-null  float64
 20  STD_Temp     16011 non-null  float64
 21  Min_Temp     16011 non-null  float64
 22  Max_Temp     16011 non-null  float64
 23  Mean_Rain    16011 non-null  float64
 24  Median_Rain  16011 non-null  float64
 25  STD_Rain     16011 non-null  float64
 26  Min_Rain     16011 non-null  float64
 27  Max_Rain     16011 non-null  float64
dtypes: float64(23), int64(3), object(2)
memory usage: 3.4+ MB

In [30]:
merged.to_csv('Combined_dataset_model.csv')

In [31]:
merged.head()

,county,land_area,biome,tc_goal,treecanopy,tc_gap,priority_i,pctpocnorm,pctpovnorm,unemplnorm,...,Mean_Temp,Median_Temp,STD_Temp,Min_Temp,Max_Temp,Mean_Rain,Median_Rain,STD_Rain,Min_Rain,Max_Rain
0,Anderson County,1.2827,Forest,0.5,0.4475,0.0525,0.507741,0.303300,0.283496,0.000000,...,67.22,67.7,0.872926,66.0,68.0,45.466,45.23,10.556187,35.32,62.36
1,Anderson County,2.1241,Forest,0.5,0.5791,0.0000,0.639673,0.858020,0.910096,0.656915,...,67.22,67.7,0.872926,66.0,68.0,45.466,45.23,10.556187,35.32,62.36
2,Anderson County,2.5378,Forest,0.5,0.4195,0.0805,0.561506,0.734242,0.486781,0.070550,...,67.22,67.7,0.872926,66.0,68.0,45.466,45.23,10.556187,35.32,62.36
3,Anderson County,3.2225,Forest,0.5,0.6449,0.0000,0.517795,0.476606,0.443385,0.000000,...,67.22,67.7,0.872926,66.0,68.0,45.466,45.23,10.556187,35.32,62.36
4,Anderson County,2.7991,Forest,0.5,0.5738,0.0000,0.526463,0.534323,0.950673,0.205986,...,67.22,67.7,0.872926,66.0,68.0,45.466,45.23,10.556187,35.32,62.36